# Generic
CONFIG_LOG=y
CONFIG_REBOOT=y

# Peripherals
CONFIG_ADC=y
CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_LED=y
CONFIG_I2C=y
CONFIG_I3C=y
CONFIG_SENSOR=y
CONFIG_SPI=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_PROMPT_UART="iot-2026:~$ "
CONFIG_ADC_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_INPUT_SHELL=y
CONFIG_LED_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_I3C_SHELL=y
CONFIG_SENSOR_SHELL=y
CONFIG_SENSOR_SHELL_STREAM=y
CONFIG_SPI_SHELL=y
CONFIG_NET_SHELL=y
